-- 计费账单 / 开票
CREATE TABLE invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no      VARCHAR(40),
    tenant_code     VARCHAR(32)  NOT NULL,
    customer        VARCHAR(128) NOT NULL,
    subscription_id BIGINT,
    plan_code       VARCHAR(32),
    type            VARCHAR(16)  NOT NULL,   -- SUBSCRIBE / CHANGE / RENEW
    amount          INT          NOT NULL,   -- 金额（元）
    currency        VARCHAR(8)   NOT NULL DEFAULT 'CNY',
    period          VARCHAR(40),
    status          VARCHAR(16)  NOT NULL,   -- PENDING / PAID / INVOICED / VOID
    created_at      TIMESTAMP    NOT NULL,
    paid_at         TIMESTAMP,
    invoiced_at     TIMESTAMP
);
CREATE INDEX idx_invoice_tenant ON invoice(tenant_code);
CREATE INDEX idx_invoice_status ON invoice(status);

-- 账单权限点
INSERT INTO permission(code,name,parent_code,type,sort) VALUES
 ('billing','计费账单',NULL,'MENU',9),
 ('billing:view','查看账单','billing','ACTION',1),
 ('billing:manage','收款/开票','billing','ACTION',2);
