-- 在线用户须知 / 用户授权(同意管理)
CREATE TABLE notice (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(16)  NOT NULL,   -- TERMS / PRIVACY / NOTICE / ANNOUNCEMENT
    title         VARCHAR(160) NOT NULL,
    content_html  TEXT         NOT NULL,
    version       INT          NOT NULL DEFAULT 1,
    status        VARCHAR(16)  NOT NULL,   -- DRAFT / PUBLISHED / ARCHIVED
    force_ack     BOOLEAN      NOT NULL DEFAULT FALSE,
    effective_at  TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL
);
CREATE INDEX idx_notice_type_status ON notice(type, status);

CREATE TABLE user_consent (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code  VARCHAR(32),
    subject      VARCHAR(128) NOT NULL,    -- 同意主体(运营账号/邮箱/手机号)
    notice_id    BIGINT       NOT NULL,
    notice_type  VARCHAR(16)  NOT NULL,
    version      INT          NOT NULL,
    action       VARCHAR(16)  NOT NULL,    -- GRANTED / REVOKED
    channel      VARCHAR(16)  NOT NULL,    -- WEB / EMAIL / API
    ip           VARCHAR(64),
    user_agent   VARCHAR(256),
    created_at   TIMESTAMP    NOT NULL
);
CREATE INDEX idx_consent_subject ON user_consent(subject);
CREATE INDEX idx_consent_notice ON user_consent(notice_id);

-- 权限点
INSERT INTO permission(code,name,parent_code,type,sort) VALUES
 ('notice','须知与授权',NULL,'MENU',10),
 ('notice:view','查看须知/授权','notice','ACTION',1),
 ('notice:edit','编辑/发布须知','notice','ACTION',2),
 ('consent:view','查看授权记录','notice','ACTION',3);
