-- 智能客服：会话 + 消息（通用 provider-agnostic，不绑定厂商）
CREATE TABLE cs_conversation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code  VARCHAR(32),
    user_ref     VARCHAR(128) NOT NULL,   -- 发起人(运营账号/访客标识)
    title        VARCHAR(160),
    status       VARCHAR(16)  NOT NULL,   -- OPEN / ESCALATED / CLOSED
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);
CREATE INDEX idx_cs_conv_user ON cs_conversation(user_ref);
CREATE INDEX idx_cs_conv_status ON cs_conversation(status);

CREATE TABLE cs_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL,
    role            VARCHAR(16) NOT NULL,   -- user / assistant / system
    content         TEXT        NOT NULL,
    created_at      TIMESTAMP   NOT NULL
);
CREATE INDEX idx_cs_msg_conv ON cs_message(conversation_id);

-- 权限点
INSERT INTO permission(code,name,parent_code,type,sort) VALUES
 ('cs','智能客服',NULL,'MENU',11),
 ('cs:use','使用客服对话','cs','ACTION',1),
 ('cs:view','查看客服会话(审计)','cs','ACTION',2);
