-- 租户自助门户:为租户开通门户访问(租户编号 + 访问码),最终客户登录后只读查看本租户数据。
CREATE TABLE tenant_portal (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(32) NOT NULL,
    access_code VARCHAR(32) NOT NULL,
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL
);
CREATE UNIQUE INDEX uk_portal_tenant ON tenant_portal(tenant_code);

INSERT INTO permission(code,name,parent_code,type,sort) VALUES
 ('tenant:portal','开通/管理自助门户','tenant','ACTION',5);
