-- 在线授权：License 激活实例（浮动席位）
CREATE TABLE license_instance (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id     VARCHAR(40)  NOT NULL,
    instance_id    VARCHAR(64)  NOT NULL,
    machine_code   VARCHAR(80),
    ip             VARCHAR(64),
    status         VARCHAR(16)  NOT NULL,  -- ACTIVE / RELEASED / EXPIRED
    activated_at   TIMESTAMP    NOT NULL,
    last_heartbeat TIMESTAMP    NOT NULL,
    CONSTRAINT uk_lic_inst UNIQUE (license_id, instance_id)
);
CREATE INDEX idx_inst_lic ON license_instance(license_id);
CREATE INDEX idx_inst_status ON license_instance(status);
