-- 邮件事务发件箱：开通邮件先入库（与租户创建同事务），再由后台异步投递+重试
CREATE TABLE email_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT,
    to_addr         VARCHAR(128) NOT NULL,
    subject         VARCHAR(256) NOT NULL,
    body_html       TEXT         NOT NULL,
    status          VARCHAR(16)  NOT NULL,   -- PENDING / SENT / FAILED
    attempts        INT          NOT NULL DEFAULT 0,
    max_attempts    INT          NOT NULL DEFAULT 5,
    next_attempt_at TIMESTAMP    NOT NULL,
    last_error      VARCHAR(512),
    created_at      TIMESTAMP    NOT NULL,
    sent_at         TIMESTAMP
);
CREATE INDEX idx_outbox_due ON email_outbox(status, next_attempt_at);
